from .user import UserViewSet
from .categoria import CategoriaViewSet
from .produto import ProdutoViewSet
from .tamanho import TamanhoViewSet
from .orcamento import OrcamentoViewSet
from .precoQtd import PrecoQtdViewSet
from .endereco import EnderecoViewSet
from .avaliacao import AvaliacaoViewSet
from .pedido import PedidoViewSet
