# Generated by Django 5.1.7 on 2025-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_alter_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=400)),
                ('validade', models.IntegerField(blank=True, default=0, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('especial', models.BooleanField(default=False)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('tamanho', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('sabor', models.CharField(max_length=100)),
            ],
        ),
    ]
