# Generated by Django 5.1.7 on 2025-06-08 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('qtnPessoas', models.IntegerField(default=0)),
                ('local', models.CharField(max_length=100)),
                ('considerações', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
