# Generated by Django 5.1.7 on 2025-06-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
