# Generated by Django 5.1.7 on 2025-06-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('qtdFatia', models.IntegerField(default=0)),
                ('massa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('formato', models.CharField(max_length=50)),
                ('tipo', models.IntegerField(choices=[(1, 'Normal'), (2, 'Especial'), (3, 'Pistache')], default=1)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
        ),
    ]
