# Generated by Django 5.1.7 on 2025-06-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanho',
            name='preco',
        ),
    ]
