# Generated by Django 5.1.7 on 2025-06-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_tamanho_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanho',
            old_name='massa',
            new_name='massakg',
        ),
    ]
