# Generated by Django 5.1.7 on 2025-06-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_massa_tamanho_massakg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='especial',
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='tipo',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Especial'), (3, 'Pistache')], default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tamanhos', to='core.tamanho'),
        ),
    ]
