# Generated by Django 5.1.7 on 2025-06-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_precoquantidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precoquantidade',
            options={'verbose_name': 'Preço Quantidade', 'verbose_name_plural': 'Preço Quantidade'},
        ),
        migrations.RemoveField(
            model_name='precoquantidade',
            name='produto',
        ),
        migrations.AddField(
            model_name='precoquantidade',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorisa', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='precoquantidade',
            name='especial',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
