# Generated by Django 5.1.7 on 2025-06-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_precoquantidade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, related_name='categorias', to='core.categoria'),
        ),
    ]
