# Generated by Django 5.1.7 on 2025-06-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_produto_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='categorias', to='core.categoria'),
        ),
    ]
