# Generated by Django 5.1.7 on 2025-06-11 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='considerações',
            new_name='consideracoes',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='precoquantidade',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precosQtds', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.tamanho'),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tamanhos', to='core.categoria'),
        ),
    ]
