# Generated by Django 5.2.3 on 2025-06-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_considerações_orcamento_consideracoes_and_more'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='produto_foto', to='uploader.image'),
        ),
    ]
