# Generated by Django 5.2.3 on 2025-06-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_produto_foto'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ManyToManyField(blank=True, default=None, related_name='produto_foto', to='uploader.image'),
        ),
    ]
