# Generated by Django 5.2.3 on 2025-07-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.endereco'),
        ),
    ]
