# Generated by Django 5.2.3 on 2025-09-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_avaliacao_options_user_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='consideracoes',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='bebidaAlcoolica',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='docinhos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='local',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='qtnPessoas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
