# Generated by Django 5.2.3 on 2025-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_orcamento_consideracoes_and_more'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='foto',
            field=models.ManyToManyField(blank=True, default=None, related_name='orcamento_foto', to='uploader.image'),
        ),
    ]
