# Generated by Django 5.2.3 on 2025-09-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_itenspedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data',
            new_name='data_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
