# Generated by Django 5.2.3 on 2025-09-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_data_pedido_data_pedido_pedido_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
