# Generated by Django 5.2.3 on 2025-10-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_pedido_data_criacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='docinhos',
            new_name='sobremesa',
        ),
    ]
