# Generated by Django 5.2.3 on 2025-10-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_docinhos_orcamento_sobremesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tamanho')),
            ],
            options={
                'unique_together': {('produto', 'tamanho')},
            },
        ),
    ]
