# Generated by Django 5.2.3 on 2025-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_produtotamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanhos',
            field=models.ManyToManyField(blank=True, related_name='produtos', through='core.ProdutoTamanho', to='core.tamanho'),
        ),
    ]
