# Generated by Django 5.2.3 on 2025-10-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_produto_tamanho_produto_tamanhos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
