# Generated by Django 5.2.3 on 2025-10-30 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedido',
            name='produto_tamanho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ProdutoTamanho', to='core.tamanho'),
        ),
    ]
