# Generated by Django 5.2.3 on 2025-10-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_itenspedido_produto_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto'),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='produto_tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.produtotamanho'),
        ),
    ]
