# Generated by Django 5.2.3 on 2025-10-30 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_itenspedido_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtotamanho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produto_tamanho', to='core.produto'),
        ),
        migrations.AlterField(
            model_name='produtotamanho',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tamanho_produto', to='core.tamanho'),
        ),
    ]
