# Generated by Django 5.2.3 on 2025-10-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_produtotamanho_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
