from .user import UserSerializer
from .categoria import CategoriaSerializer
from .produto import ProdutoSerializer
from .produto import ProdutoListSerializer
from .produto import ProdutoRetrieveSerializer
from .tamanho import TamanhoSerializer
from .tamanho import TamanhoListSerializer
from .tamanho import TamanhoRetrieveSerializer
from .orcamento import OrcamentoSerializer
from .orcamento import OrcamentoListSerializer
from .orcamento import OrcamentoRetriveSerializer
from .precoQtd import PrecoQtdSerializer
from .precoQtd import PrecoQtdListSerializer
from .precoQtd import PrecoQtdRetrieveSerializer
from .endereco import EnderecoSerializer
from .avaliacao import AvaliacaoSerializer
from .avaliacao import AvaliacaoListSerializer
from .avaliacao import AvaliacaoRetriveSerializer
from .pedido import PedidoSerializer, PedidoCreateUpdateSerializer, ItensPedidoCreateUpdateSerializer, ItensPedidoSerializer, PedidoListSerializer, ItensPedidoListSerializer