from .user import UserSerializer
from .categoria import CategoriaSerializer
from .produto import ProdutoSerializer
from .produto import ProdutoListSerializer
from .produto import ProdutoRetrieveSerializer
from .tamanho import TamanhoSerializer
from .tamanho import TamanhoListSerializer
from .tamanho import TamanhoRetrieveSerializer
from .orcamento import OrcamentoSerializer
from .orcamento import OrcamentoListSerializer
from .orcamento import OrcamentoRetriveSerializer
from .precoQtd import PrecoQtdSerializer
from .precoQtd import PrecoQtdListSerializer
from .precoQtd import PrecoQtdRetrieveSerializer
